name: ci
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*"
env:
  IMAGE_NAME: canal-server #这是您的镜像名
jobs:
  get-tags:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    outputs:
      TAGS: ${{ steps.set-output-id.output.TAGS }}
    steps:
      - uses: actions/checkout@v3
      - name: set-output
        id: set-output-id
        shell: bash
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            ## tag names like 'v0.0.1'
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "TAGS=$VERSION" >> "$GITHUB_OUTPUT"
  push-ghcr:
    needs: get-tags
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    defaults:
      run:
        working-directory: src/canal-server
    steps:
      - uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: download artifact
        run: bash build.sh download
      - name: test
        run:
          - echo "${{ needs.get-tags.outputs.TAGS }}"
      - name: Build && Push
        uses: docker/build-push-action@v4
        with:
          context: src/canal-server
          file: src/canal-server/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.get-tags.outputs.TAGS }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
